name: Build .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x       
    - name: Restore dependencies
      run: dotnet restore WebCon.BpsExt.Signing.Autenti.sln
    - name: Build
      run: dotnet build WebCon.BpsExt.Signing.Autenti.sln  --no-restore --configuration Release 
    - uses: actions/upload-artifact@v3
      with:
        name: WebCon.BpsExt.Signing.Autenti
        path: |
          WebCon.BpsExt.Signing.Autenti/bin/Release/netstandard2.0/WebCon.BpsExt.Signing.Autenti.dll
          WebCon.BpsExt.Signing.Autenti/bin/Release/netstandard2.0/WebCon.BpsExt.Signing.Autenti.json
          WebCon.BpsExt.Signing.Autenti/bin/Release/netstandard2.0/Newtonsoft.Json.dll
          
